# See docker-compose.yml for further descriptions and configuration details of each service

wordpress:
  extends:
    file: docker-compose.yml
    service: wordpress
  build: .
  privileged: true
  restart: "no"
  environment:
    - CONSUL=consul
  links:
    - consul:consul
  ports:
    - "80"

consul:
  extends:
    file: docker-compose.yml
    service: consul
  restart: "no"
  ports:
    - 8500:8500

nfs:
  extends:
    file: docker-compose.yml
    service: nfs
  privileged: true
  restart: "no"
  environment:
    - CONSUL=consul
  links:
    - consul:consul
  ports:
    - 111
    - 1892:1892
    - 2049

mysql:
  extends:
    file: docker-compose.yml
    service: mysql
  restart: "no"
  environment:
    - CONSUL=consul
  links:
    - consul:consul
  ports:
    - 3306

memcached:
  extends:
    file: docker-compose.yml
    service: memcached
  restart: "no"
  environment:
    - CONSUL=consul
  links:
    - consul:consul

nginx:
  extends:
    file: docker-compose.yml
    service: nginx
  build: nginx/
  restart: "no"
  environment:
    - CONSUL=consul
  links:
    - consul:consul
  ports:
    - 80:80

prometheus:
  extends:
    file: docker-compose.yml
    service: prometheus
  restart: "no"
  environment:
    - CONSUL=consul
  links:
    - consul:consul
  ports:
    - 9090:9090
